### ISSUE TITLE
RAB Grandroid turned on by default 8.5

### ISSUE THREAD

**Issue by indiamcq** [sillsdev/appbuilder-buildengine-api#40]
Cause: Creating new RAB app
Issue: Grandroid was turned on by default
Expected: Grandroid would not be turned on
Workaround: Turn off manually
Note: I was creating a new project to compare to a crashing project. When comparing the two .appdef files I was surprised to see Grandroid turned on.
Affects version: 8.5
Priority: low but it will cause issues
[RAB1 test2.zip](https://github.com/sillsdev/appbuilder-buildengine-api/files/5978665/RAB1.test2.zip)

**Comment by chrisvire** [comment]
Did you mean to create this on app-builders project?

**Comment by indiamcq** [comment]
Yes Chris that was my intent, no due dillegence. Sorry. You can kill it here.

**Comment by chrisvire** [comment]
Wrong project
